types = {}

types["animals"] = [
    "Aardvark",
    "Afghan Hound",
    "Altum Angel Fish",
    "Andean Condor",
    "Angler Fish",
    "Angora Rabbit",
    "Ant",
    "Anteater",
    "Antelope",
    "Arctic Fox",
    "Armadillo",
    "Axolotl",
    "Baboon",
    "Badger",
    "Barn Owl",
    "Basking Shark",
    "Bat",
    "Bear",
    "Bearded Vulture",
    "Beaver",
    "Bedlington Terrier",
    "Bee",
    "Binturong",
    "Bison",
    "Black Angel Fish",
    "Black Emporer Scorpion",
    "Black Lace Angel Fish",
    "Black Vulture",
    "Blue Ringed Octopus",
    "Blue Whale",
    "Bongo",
    "Buffalo",
    "Bull",
    "Bull Terrier",
    "Bush Viper",
    "Butterfly" ,
    "Camal",
    "Carpet Chameleon",
    "Cassowary",
    "Cat Fish",
    "Chamois",
    "Chicken",
    "Chinchilla",
    "Chinese Crested Dog",
    "Chinese Shar Pei",
    "Chocolate Angel Fish",
    "Chocolate Ghost Angel Fish",
    "Click Beetle",
    "Clydesdale",
    "Coati",
    "Cobra",
    "Colossal Squid",
    "Costa Rican Hair Caterpillar",
    "Cottontop Tamarin",
    "Crab",
    "Crane",
    "Crocodile",
    "Dachshund",
    "Deer",
    "Devils Flower Mantis",
    "Dormouse",
    "Dragonfly",
    "Dutch Landrace Goat",
    "Eagle",
    "Earwig",
    "Echidna",
    "Egyptian Vulture",
    "Elephant",
    "Elephant Seal",
    "Emperor Tamarin",
    "Emu",
    "English Cocker Spaniel",
    "Fennec Fox",
    "Ferret",
    "Flabellina Affinis",
    "Flamingo",
    "Fly",
    "Flying Squirrel",
    "Fox",
    "FrigateBird",
    "Frilled Lizard",
    "Frilled Shark",
    "Gar",
    "Geoffroys Tamarin",
    "Gharial Crocodile",
    "Giant Devils Flower Mantis",
    "Giraffe",
    "Glaucus Atlandicus",
    "Glow Worm",
    "Goblin Shark",
    "Gorilla",
    "Grasshopper",
    "Great Dane",
    "Great White Shark",
    "Grey Mouse Lemur",
    "Griffon Vulture",
    "Grizzly Bear",
    "Guinea Fowl",
    "Gunnison Sage - Grouse",
    "Guppy",
    "Gypsy Horse",
    "Hammer Head Shark",
    "Hawk",
    "Hawk",
    "Hermit Crab",
    "Highland Cattle",
    "Hippopotamus",
    "Hoopoe",
    "Horned Lizard",
    "Hornet",
    "Horse",
    "Humming Bird",
    "Humpback Whale",
    "Hyena",
    "Ibis",
    "Iguana",
    "Indian Flower Mantis",
    "Indri",
    "Jackson Chameleon",
    "Japanese Macaque",
    "Jelly Fish",
    "Kangaroo",
    "Killer Whales",
    "King Crab",
    "King Vulture",
    "Kiwi",
    "Koala",
    "Komodo Dragon",
    "Lady Bug",
    "Lemming",
    "Lemurs",
    "Lightning Bug",
    "Lion",
    "Lion Fish",
    "Lion's Mane Jellyfish",
    "Llama",
    "Lobster",
    "Long Eared Owl",
    "Longhorn Beetle",
    "Manatee",
    "Manta Ray",
    "Mantis Shrimp",
    "Markhor",
    "MayFly",
    "Meerkat",
    "Millipedes",
    "Mongoose",
    "Monitor Lizard",
    "Moose",
    "Moray Eal",
    "Mosquito",
    "Moth",
    "Narwhal",
    "Nautilus",
    "Neapolitan Mastiff",
    "Northern Royal Flycatcher",
    "Oarfish",
    "Octopus",
    "Okapi",
    "Opossum",
    "Orchis Mantis",
    "Ostrich",
    "Panda Bear",
    "Parrot",
    "Peacock",
    "Pelican",
    "Penguins",
    "Pig",
    "Pink Fairy Armadillo",
    "Pink Nillipede",
    "Pitbull",
    "Polar Bear",
    "Poodle",
    "Porcupine",
    "Possums",
    "Prawn",
    "Praying MAntis",
    "Pteraeolidia Ianthina",
    "Puffin",
    "Puli",
    "Puss Caterpillar",
    "Puss Mouth",
    "Pygmy Marmoset",
    "Quail",
    "Quetzal",
    "Rabbit",
    "Racoon",
    "Radiated Tortoise",
    "Ram",
    "Raptor",
    "Rat",
    "Rattle Snake",
    "Rattle Snake",
    "Red Panda",
    "Rhinoceros",
    "Rhinoceros Beetle",
    "River Dolphin",
    "Rooster",
    "Roseate Spoonbill",
    "Royal Spider",
    "Saber Tooth Tiger",
    "Saddleback Caterpiller",
    "Sand Lizard",
    "Saola",
    "Sea Angel",
    "Sea Dragon",
    "Sea Horse",
    "Sea Otter",
    "Sea Turtle",
    "Seal",
    "Sheep",
    "Shrimp",
    "Siamese Fighting Fish",
    "Skull",
    "Sloth",
    "Snail",
    "Snapping Turtle",
    "Sperm Whale",
    "Spiny Flower Mantis",
    "Spiny Oak Slug Caterpillar",
    "Squirrel",
    "Stag Beetle",
    "Stegosaurus",
    "Stick Insect",
    "Sting Ray",
    "Stinging Roase Caterpillar",
    "Sumatran Orangutan",
    "Swan",
    "Tamarin",
    "Tang",
    "Tapir",
    "Tarsier",
    "Tawny Owl",
    "Tethy Fimbria",
    "Thorny Devil",
    "Tiger",
    "Tiger Salamander",
    "Tortoise",
    "Toucan",
    "Tree Frog",
    "Tropicbird",
    "Tuatara",
    "Turkey",
    "Tyrannosaurus Rex",
    "Uakari Monkey",
    "Umbrella Bird",
    "Vampire Squid",
    "Veiled Chameleon",
    "Velvet Ant",
    "Vulture",
    "Walrus",
    "Warthog",
    "Wasp",
    "Weasel",
    "Weevil",
    "Whale Shark",
    "Wildebeest",
    "Wolf",
    "Wombat",
    "Woodlouse",
    "Wooly Mammoth",
    "Yoda Bat",
    "Zebra",
    "Zebu",
    "Zorse",
]

types["bodies"] = [
    "Boney",
    "Bulky",
    "Chubby",
    "Fat",
    "Lean",
    "Muscular",
    "Skinny",
    "Stout",
]

types["skins"] = [
    "Amphibious",
    "Bone",
    "Decayed",
    "Dry",
    "Ethereal",
    "Hairy",
    "Liquid",
    "Metal",
    "Molten",
    "Rock",
    "Scaley: Dry",
    "Scaley: Fish",
    "Spiked",
]
